// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExportInterviewExcelTemplate(arg1:string):Promise<void>;

export function GenerateInterviewReportPDF(arg1:any,arg2:string,arg3:string,arg4:string):Promise<void>;

export function GetExcelSheets(arg1:string):Promise<Array<string>>;

export function MergeReportAndResumePDF(arg1:string,arg2:string,arg3:string):Promise<void>;

export function MessageDialog(arg1:string,arg2:string,arg3:string):Promise<string>;

export function ReadDataFromExcel(arg1:string,arg2:string):Promise<Array<any>>;

export function SelectDirectory():Promise<string>;

export function SelectFileDialog():Promise<string>;
