// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExportInterviewExcelTemplate(arg1) {
  return window['go']['main']['App']['ExportInterviewExcelTemplate'](arg1);
}

export function GenerateInterviewReportPDF(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GenerateInterviewReportPDF'](arg1, arg2, arg3, arg4);
}

export function GetExcelSheets(arg1) {
  return window['go']['main']['App']['GetExcelSheets'](arg1);
}

export function MergeReportAndResumePDF(arg1, arg2, arg3) {
  return window['go']['main']['App']['MergeReportAndResumePDF'](arg1, arg2, arg3);
}

export function MessageDialog(arg1, arg2, arg3) {
  return window['go']['main']['App']['MessageDialog'](arg1, arg2, arg3);
}

export function ReadDataFromExcel(arg1, arg2) {
  return window['go']['main']['App']['ReadDataFromExcel'](arg1, arg2);
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}

export function SelectFileDialog() {
  return window['go']['main']['App']['SelectFileDialog']();
}
